-- MYRA schema dump: myra_archive.db (archive)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE fundamentals_snapshots (
    symbol      TEXT NOT NULL,
    as_of_date  TEXT NOT NULL,
    snapshot_id TEXT NOT NULL,
    source      TEXT,
    captured_at TEXT NOT NULL,
    row_sha256  TEXT NOT NULL,
    row_json    TEXT NOT NULL,
    PRIMARY KEY (symbol, as_of_date)
)

CREATE TABLE raw_traction_archive (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    fetched_at   TEXT NOT NULL,
    source_url   TEXT NOT NULL,
    source_month TEXT,
    sha256       TEXT NOT NULL,
    byte_size    INTEGER,
    symbol_count INTEGER,
    raw_path     TEXT NOT NULL,
    recorded_at  TEXT NOT NULL
)

CREATE INDEX ix_fund_snap_date ON fundamentals_snapshots (as_of_date)
