-- MYRA schema dump: myra_calendar.db (calendar)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE market_calendar (
            date TEXT PRIMARY KEY,
            is_trading_day INTEGER NOT NULL,
            holiday_name TEXT
        , session_type TEXT)
