-- MYRA schema dump: myra_governance.db (governance)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE ias_history (
                    symbol TEXT,
                    date TEXT,
                    ias_score REAL,
                    ias_rank REAL,
                    tags TEXT,
                    PRIMARY KEY (symbol, date)
                )

CREATE TABLE pledged_history (
                    symbol TEXT,
                    date TEXT,
                    promoter_holding REAL,
                    pledged_pct REAL,
                    change_qoq REAL,
                    PRIMARY KEY (symbol, date)
                )

CREATE TABLE sast_disclosures (
                    disclosure_id TEXT PRIMARY KEY,
                    symbol TEXT,
                    date TEXT,
                    acq_name TEXT,
                    qty_pct REAL,
                    type TEXT
                )

CREATE TABLE shareholding_history (
                    symbol TEXT,
                    date TEXT,
                    fii_pct REAL,
                    dii_pct REAL,
                    promoter_pct REAL,
                    PRIMARY KEY (symbol, date)
                )
