-- MYRA schema dump: myra_institutional.db (institutional)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE block_deals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                date TEXT NOT NULL,
                security_name TEXT,
                client_name TEXT,
                buy_sell TEXT,
                quantity INTEGER,
                price REAL,
                trade_value REAL,
                source TEXT DEFAULT 'NSE-MCP',
                UNIQUE(symbol, date, client_name, buy_sell)
            )

CREATE TABLE block_deals_historical (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT,
            date TEXT,
            security_name TEXT,
            client_name TEXT,
            buy_sell TEXT,
            quantity REAL,
            price REAL,
            trade_value REAL,
            source TEXT
        )

CREATE TABLE bulk_deals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                date TEXT NOT NULL,
                security_name TEXT,
                client_name TEXT,
                buy_sell TEXT,
                quantity INTEGER,
                price REAL,
                trade_value REAL,
                source TEXT DEFAULT 'NSE-MCP',
                UNIQUE(symbol, date, client_name, buy_sell)
            )

CREATE TABLE bulk_deals_historical (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT,
            date TEXT,
            security_name TEXT,
            client_name TEXT,
            buy_sell TEXT,
            quantity REAL,
            price REAL,
            trade_value REAL,
            source TEXT
        )

CREATE TABLE corporate_actions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                symbol TEXT NOT NULL,
                date TEXT NOT NULL,
                security_name TEXT,
                action_type TEXT,
                ex_date TEXT,
                record_date TEXT,
                source TEXT DEFAULT 'NSE-MCP',
                UNIQUE(symbol, date, action_type)
            )

CREATE TABLE fii_dii_daily (
                date TEXT PRIMARY KEY,
                fii_net_buy REAL,
                dii_net_buy REAL,
                source TEXT DEFAULT 'NSE-MCP'
            )

CREATE TABLE fii_dii_history (
                    symbol TEXT,
                    date TEXT,
                    fii_pct REAL,
                    dii_pct REAL,
                    promoter_pct REAL,
                    pledged_pct REAL,
                    fii_change REAL,
                    dii_change REAL,
                    car_ratio REAL,
                    is_hidden_accumulation INTEGER DEFAULT 0,
                    PRIMARY KEY (symbol, date)
                )

CREATE TABLE insider_trades (
                    symbol TEXT,
                    acq_name TEXT,
                    category TEXT,
                    type TEXT,
                    mode TEXT,
                    value_cr REAL,
                    avg_price REAL,
                    date TEXT,
                    PRIMARY KEY (symbol, acq_name, date, value_cr)
                )

CREATE TABLE institutional_owners (
                    symbol TEXT,
                    owner_name TEXT,
                    owner_type TEXT,
                    shares_held INTEGER,
                    pct_held REAL,
                    date TEXT,
                    PRIMARY KEY (symbol, owner_name, date)
                )

CREATE TABLE large_deals (
            symbol TEXT,
            type TEXT,
            client TEXT,
            buy_sell TEXT,
            qty INTEGER,
            price REAL,
            date TEXT, client_name TEXT, deal_type TEXT, value REAL,
            PRIMARY KEY (symbol, client, date, qty, price)
        )

CREATE TABLE sync_metadata (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )

CREATE INDEX idx_deals_sym ON large_deals (symbol)

CREATE INDEX idx_insider_sym ON insider_trades (symbol)
