-- MYRA schema dump: myra_metadata.db (meta)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE benchmarks (symbol TEXT, date TEXT, close REAL, PRIMARY KEY (symbol, date))

CREATE TABLE bhm1_cooldown (
    symbol          TEXT NOT NULL PRIMARY KEY,
    signal_date     TEXT,
    floor_year_low  REAL,
    run_min_year_low REAL,
    updated_at      TEXT
)

CREATE TABLE bhm1_positions (
    symbol             TEXT NOT NULL PRIMARY KEY,
    first_entry_date   TEXT,
    last_tranche_date  TEXT,
    n_tranches         INTEGER,
    blended_basis      REAL,
    updated_at         TEXT
, tranche_prices TEXT)

CREATE TABLE doctor_runs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            when_utc        DATETIME,
            issues_found    INTEGER,
            issues_fixed    INTEGER,
            issues_failed   INTEGER,
            critical_json   TEXT
        )

CREATE TABLE etf_blocklist (
            symbol      TEXT PRIMARY KEY,
            added_date  TEXT,
            source      TEXT
        )

CREATE TABLE etf_sync_log (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            sync_date   TEXT,
            source      TEXT,
            count       INTEGER,
            status      TEXT
        )

CREATE TABLE index_constituents (
        index_name TEXT NOT NULL,
        symbol TEXT NOT NULL,
        added_date TEXT,
        PRIMARY KEY (index_name, symbol)
    )

CREATE TABLE index_membership_history (
        index_name TEXT NOT NULL,
        symbol     TEXT NOT NULL,
        from_date  TEXT NOT NULL,
        to_date    TEXT NOT NULL
    )

CREATE TABLE lineage_tracking (
                    dataset_name TEXT,
                    fetch_time TEXT,
                    source_url TEXT,
                    rows_processed INTEGER,
                    status TEXT,
                    transformations_applied TEXT,
                    PRIMARY KEY (dataset_name, fetch_time)
                )

CREATE TABLE metadata (key TEXT PRIMARY KEY, value TEXT)

CREATE TABLE sb_positions (
    symbol          TEXT NOT NULL PRIMARY KEY,
    entry_date      TEXT,
    entry_price     REAL,
    ever_activated  INTEGER DEFAULT 0,
    highest_close   REAL,
    updated_at      TEXT
)

CREATE TABLE symbols_master (
                    symbol TEXT PRIMARY KEY,
                    first_seen TEXT,
                    last_seen TEXT,
                    in_active_universe INTEGER DEFAULT 0,
                    in_nifty500 INTEGER DEFAULT 0,
                    sector TEXT,
                    industry TEXT,
                    raw_sector TEXT,
                    raw_industry TEXT,
                    source TEXT,
                    confidence REAL,
                    last_updated_sector TEXT,
                    sector_locked INTEGER DEFAULT 0,
                    is_active INTEGER DEFAULT 1,
                    instrument_type TEXT DEFAULT 'EQUITY',
                    last_fundamental_update TEXT
                , bse_scrip_code TEXT, name TEXT)

CREATE TABLE sync_log (
                task_name   TEXT PRIMARY KEY,
                last_run    TEXT
            , last_status TEXT DEFAULT 'unknown', error_message TEXT DEFAULT NULL, progress_pct REAL DEFAULT 0)

CREATE TABLE task_registry (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                status TEXT DEFAULT 'running',
                message TEXT DEFAULT '',
                progress REAL,
                eta TEXT,
                task_type TEXT DEFAULT 'indefinite',
                safe_to_exit INTEGER DEFAULT 1,
                started_at TEXT NOT NULL,
                updated_at TEXT,
                expiry TEXT,
                data TEXT DEFAULT '{}'
            )

CREATE INDEX idx_constituents_symbol ON index_constituents(symbol)

CREATE INDEX idx_imh_lookup ON index_membership_history (index_name, symbol, from_date, to_date)

CREATE INDEX idx_master_active ON symbols_master (in_active_universe)

CREATE INDEX idx_master_industry ON symbols_master (industry)

CREATE INDEX idx_master_nifty500 ON symbols_master (in_nifty500)

CREATE INDEX idx_master_sector ON symbols_master (sector)

CREATE INDEX idx_symbols_sector ON symbols_master(sector)
