-- MYRA schema dump: myra_portfolio.db (myra_portfolio)
-- UNREGISTERED in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE fundamental_cache (
            symbol TEXT PRIMARY KEY,
            pe REAL,
            sector TEXT,
            market_cap REAL,
            fetched_at TEXT DEFAULT (datetime('now','localtime'))
        )

CREATE TABLE holdings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL UNIQUE,
            category TEXT DEFAULT 'NSE EQ',
            net_qty INTEGER NOT NULL,
            avg_price REAL NOT NULL,
            created_at TEXT DEFAULT (datetime('now','localtime')),
            updated_at TEXT DEFAULT (datetime('now','localtime'))
        )

CREATE TABLE industry_cache (
            symbol TEXT PRIMARY KEY,
            industry TEXT,
            yf_sector TEXT,
            fetched_at TEXT DEFAULT (datetime('now','localtime'))
        )

CREATE TABLE live_price_cache (
                symbol TEXT PRIMARY KEY,
                ltp REAL,
                change REAL,
                change_pct REAL,
                previous_close REAL,
                fetched_at TEXT DEFAULT (datetime('now','localtime'))
            )

CREATE TABLE portfolio_meta (
            key TEXT PRIMARY KEY,
            value TEXT
        )

CREATE TABLE price_cache (
            symbol TEXT PRIMARY KEY,
            latest_close REAL,
            previous_close REAL,
            latest_date TEXT,
            updated_at TEXT DEFAULT (datetime('now','localtime'))
        )

CREATE TABLE snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT NOT NULL,
            total_invested REAL NOT NULL,
            total_current REAL NOT NULL,
            overall_pnl REAL NOT NULL,
            overall_pnl_pct REAL NOT NULL,
            day_pnl REAL NOT NULL,
            day_pnl_pct REAL NOT NULL,
            created_at TEXT DEFAULT (datetime('now','localtime'))
        )

CREATE TABLE transactions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            qty INTEGER,
            price REAL,
            notes TEXT,
            created_at TEXT DEFAULT (datetime('now','localtime'))
        )
