-- MYRA schema dump: myra_news.db (myra_news)
-- UNREGISTERED in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE news_sentiment (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ticker TEXT NOT NULL,
            headline TEXT NOT NULL,
            source TEXT,
            published_at TEXT,
            sentiment_label TEXT,
            sentiment_score REAL,
            created_at TEXT DEFAULT (datetime('now', 'localtime')), url TEXT, language TEXT, tone REAL, domain TEXT, company_name TEXT,
            UNIQUE(ticker, headline, published_at)
        )

CREATE INDEX idx_ticker_date
        ON news_sentiment(ticker, published_at DESC)
