-- MYRA schema dump: myra_cache_network.db (network_cache)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE cache (
                key TEXT PRIMARY KEY,
                value BLOB,
                created_at TEXT NOT NULL DEFAULT (datetime('now'))
            )
