-- MYRA schema dump: myra_options.db (options)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE option_chain (
            symbol TEXT,
            kind TEXT,
            spot REAL,
            pcr REAL,
            regime TEXT,
            total_ce_oi INTEGER,
            total_pe_oi INTEGER,
            atm_strike REAL,
            expiry TEXT,
            strike_count INTEGER,
            raw_json TEXT,
            created_at TEXT
        )

CREATE TABLE pcr_snapshot (
            index_symbol TEXT PRIMARY KEY,
            pcr REAL,
            regime TEXT,
            spot REAL,
            expiry TEXT,
            updated_at TEXT
        )
