-- MYRA schema dump: myra_scoring.db (scoring)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE fundamental_scores (
            symbol TEXT NOT NULL,
            date TEXT NOT NULL,
            growth_score REAL,
            quality_score REAL,
            stability_score REAL,
            risk_score REAL,
            total_funda_score REAL,
            grade TEXT,
            PRIMARY KEY (symbol, date)
        )

CREATE TABLE mcap_rank_daily (
    symbol     TEXT NOT NULL,
    date       TEXT NOT NULL,
    mcap_cr    REAL,
    mcap_rank  INTEGER,
    PRIMARY KEY (symbol, date)
)

CREATE TABLE ranking_history (
            symbol TEXT NOT NULL,
            date TEXT NOT NULL,
            rank_nifty500 INTEGER,
            rank_sector INTEGER,
            PRIMARY KEY (symbol, date)
        )
