-- MYRA schema dump: myra_technical.db (technical)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE ingestion_rejects (
                    symbol TEXT,
                    date TEXT,
                    reason TEXT,
                    raw_values TEXT,
                    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
                )

CREATE TABLE launchpad_events (
                    symbol TEXT,
                    trigger_date TEXT,
                    trigger_peak_price REAL,
                    digestion_low_price REAL,
                    digestion_low_date TEXT,
                    launchpad_date TEXT,
                    launchpad_close REAL,
                    breakout_date TEXT,
                    breakout_close REAL,
                    return_pct REAL,
                    days_to_breakout INTEGER,
                    success INTEGER,
                    max_drawdown_pct REAL,
                    min_range_atr_ratio REAL,
                    min_vol_ratio REAL
                )

CREATE TABLE launchpad_features (
                    symbol TEXT,
                    trigger_date TEXT,
                    breakout_date TEXT,
                    return_pct REAL,
                    max_drawdown_pct REAL,
                    days_to_breakout REAL,
                    success INTEGER,
                    del_zscore_min REAL,
                    del_zscore_mean REAL,
                    range_atr_min REAL,
                    vol_ratio_min REAL,
                    digestion_days INTEGER,
                    close_min REAL,
                    vwap_min REAL,
                    volume_min INTEGER,
                    liquidity_min REAL,
                    fvg_freshness_min REAL
                )

CREATE TABLE technical_data (
    symbol TEXT,
    date TEXT,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    volume INTEGER,
    delivery INTEGER,
    trades INTEGER,
    vwap REAL,
    delivery_pct REAL,
    delivery_ratio REAL,
    delivery_qty REAL,
    stock_return REAL,
    market_return REAL,
    delivery_divergence_score REAL,
    volatility_compression_score REAL,
    relative_volume_score REAL,
    nifty_outperformance_score REAL,
    delivery_source TEXT,
    bullish_fvg INTEGER,
    bearish_fvg INTEGER,
    fvg_top REAL,
    fvg_bottom REAL,
    fvg_boundary REAL,
    fvg_freshness REAL,
    swing_high REAL,
    swing_low REAL,
    liquidity_distance REAL,
    htf_bullish INTEGER,
    htf_bearish INTEGER,
    mtf_bullish INTEGER,
    mtf_bearish INTEGER,
    trend_alignment INTEGER,
    delivery_ma_60 REAL,
    has_bullish_fvg INTEGER,
    sma_50 REAL,
    high_52w REAL,
    low_52w REAL, sma_5 REAL, sma_10 REAL, sma_15 REAL, sma_200 REAL,
    PRIMARY KEY (symbol, date)
)

CREATE INDEX idx_lp_active ON launchpad_events(success, trigger_date)

CREATE INDEX idx_lp_sym ON launchpad_events(symbol, trigger_date)

CREATE INDEX idx_lpf_sym ON launchpad_features(symbol, trigger_date)

CREATE INDEX idx_tech_date ON technical_data(date)

CREATE INDEX idx_tech_date_symbol ON technical_data(date, symbol)

CREATE INDEX idx_tech_symbol ON technical_data(symbol)

CREATE INDEX idx_tech_symbol_date ON technical_data(symbol, date)
