-- MYRA schema dump: myra_valuation.db (valuation)
-- Registered in DB_MAP
-- Generated by scripts/dump_schema.py
-- Read-only dump: DDL only, no row data.

CREATE TABLE full_fundamental_cache (
            symbol TEXT PRIMARY KEY,
            data_json TEXT,
            source TEXT,
            last_updated TEXT
        )

CREATE TABLE fund_cross_buy (
    symbol TEXT,
    month TEXT,
    total_funds INTEGER,
    large_funds INTEGER,
    mid_funds INTEGER,
    small_funds INTEGER,
    multi_funds INTEGER,
    other_funds INTEGER,
    cross_buy_ratio REAL,
    signal_tag TEXT,
    last_updated TEXT,
    PRIMARY KEY (symbol, month)
)

CREATE TABLE fund_traction (
    symbol          TEXT    NOT NULL,
    month           TEXT    NOT NULL,   -- YYYY-MM
    traction_score  REAL,
    number_of_funds INTEGER,
    adds_new        INTEGER,
    reduces_closes  INTEGER,
    sma_30          REAL,
    month_end_close REAL,
    close_latest    REAL,
    pct_vs_sma      REAL,
    PRIMARY KEY (symbol, month)
)

CREATE TABLE fundamentals (
            symbol TEXT PRIMARY KEY,
            pe REAL,
            roe REAL,
            eps REAL,
            book_value REAL,
            market_cap REAL,
            sector TEXT,
            last_updated TEXT
        , profit_growth REAL, sales_growth REAL, debt_to_equity REAL, inst_holding REAL, dividend_yield REAL, date TEXT, sector_pe REAL, face_value REAL, issued_size REAL, net_margin REAL, roe_ttm REAL, daily_volatility REAL, annual_volatility REAL, impact_cost REAL, source_ms TEXT, source_nse TEXT, peRatio REAL, priceToBook REAL, priceToSales REAL, earningsPerShare REAL, bookValuePerShare REAL, revenueGrowth REAL, earningsGrowth REAL, marketCap REAL, enterpriseValue REAL, debtToEquity REAL, returnOnEquity REAL, returnOnAssets REAL, operatingMargin REAL, grossMargin REAL, netMargin REAL, dividendYield REAL, payoutRatio REAL, currentRatio REAL, quickRatio REAL, freeCashFlowYield REAL, beta REAL, free_float_pct REAL, free_float_market_cap REAL, free_float_shares REAL, insider_holding_pct REAL, public_holding_pct REAL, industry TEXT, shares_outstanding REAL, promoter_holding_pct REAL, last_fundamental_update TEXT, operating_margin REAL, gross_margin REAL, free_cash_flow_yield REAL, current_ratio REAL, quick_ratio REAL)

CREATE TABLE quarterly_results (
            symbol TEXT,
            report_date TEXT,
            revenue REAL,
            net_profit REAL,
            eps REAL,
            opm_pct REAL, period_end TEXT,
            PRIMARY KEY (symbol, report_date)
        )

CREATE TABLE screener_fundamentals (
            symbol TEXT PRIMARY KEY,
            pbv REAL,
            roce REAL,
            last_updated TEXT
        )

CREATE TABLE sync_metadata (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TEXT NOT NULL
)

CREATE TABLE upstox_balance_sheet (
            isin TEXT NOT NULL,
            symbol TEXT NOT NULL,
            period TEXT NOT NULL,
            report_type TEXT NOT NULL,
            time_period TEXT NOT NULL,
            units_in TEXT,
            total_asset REAL,
            total_liability REAL,
            raw_json TEXT,
            fetched_at TEXT,
            PRIMARY KEY (isin, period, report_type, time_period)
        )

CREATE TABLE "upstox_cache" (
                    isin TEXT,
                    endpoint TEXT,
                    hash TEXT,
                    data_json TEXT,
                    last_updated TEXT, json_data TEXT, fetched_at TEXT,
                    PRIMARY KEY (isin, endpoint)
                )

CREATE TABLE upstox_cash_flow (
            isin TEXT NOT NULL,
            symbol TEXT NOT NULL,
            period TEXT NOT NULL,
            report_type TEXT NOT NULL,
            time_period TEXT NOT NULL,
            units_in TEXT,
            operating REAL,
            investing REAL,
            financing REAL,
            operating_change TEXT,
            investing_change TEXT,
            financing_change TEXT,
            raw_json TEXT,
            fetched_at TEXT,
            PRIMARY KEY (isin, period, report_type, time_period)
        )

CREATE TABLE upstox_competitors (
            isin TEXT NOT NULL,
            symbol TEXT NOT NULL,
            competitor_instrument_key TEXT NOT NULL,
            competitor_sector TEXT,
            company_profile TEXT,
            sector_market_cap_inr REAL,
            raw_json TEXT,
            fetched_at TEXT,
            PRIMARY KEY (isin, competitor_instrument_key)
        )

CREATE TABLE upstox_corporate_actions (
            isin TEXT NOT NULL,
            symbol TEXT NOT NULL,
            name TEXT NOT NULL,
            expiry_date TEXT NOT NULL,
            amount REAL,
            ratio TEXT,
            event_details_json TEXT,
            raw_json TEXT,
            fetched_at TEXT,
            PRIMARY KEY (isin, name, expiry_date)
        )

CREATE TABLE upstox_income_statement (
            isin TEXT NOT NULL,
            symbol TEXT NOT NULL,
            period TEXT NOT NULL,
            report_type TEXT NOT NULL,
            time_period TEXT NOT NULL,
            units_in TEXT,
            revenue REAL,
            operating_profit REAL,
            net_profit REAL,
            revenue_change TEXT,
            operating_profit_change TEXT,
            net_profit_change TEXT,
            raw_json TEXT,
            fetched_at TEXT,
            PRIMARY KEY (isin, period, report_type, time_period)
        )

CREATE INDEX idx_fund_traction_month ON fund_traction(month)

CREATE INDEX idx_funda_sector ON fundamentals(sector)
