#!/usr/bin/env python
"""
Generate schema/ground-truth docs for MYRA's SQLite sidecars.

Outputs:
  schema/<dbname>.sql            - full DDL (CREATE TABLE / CREATE INDEX) per DB, no data
  schema/schema_manifest.json    - per-DB list of tables: columns, types, NOT NULL, PK, row counts

Read-only by construction:
  * Every database is opened with the sqlite3 URI-mode flag `?mode=ro`.
    A read-only connection cannot write to the file; a write attempt raises
    "attempt to write a readonly database".
  * PRAGMA query_only=ON is additionally set on each connection as a second
    guard rail against accidental writes.
  * The script only ever executes SELECTs (sqlite_master / table_info / count).

Scope:
  * All 9 databases registered in myra_app.librarian_core.LibrarianCore.DB_MAP.
  * myra_news.db and myra_portfolio.db exist on disk under DB_DIR but are NOT in
    DB_MAP (portfolio is gitignored). They are dumped too (read directly from
    DB_DIR by filename) and explicitly flagged "on-disk but unregistered in
    DB_MAP" in the manifest via "registered": false.

Also cross-checks the on-disk schemas against myra_app.schema_registry.py's 36
table definitions and prints any mismatch to stdout (without fixing anything).

Usage:
  python scripts/dump_schema.py
"""

import json
import os
import sqlite3
import sys

# Ensure the repo root is importable regardless of CWD.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from myra_app.constants import DB_DIR, PROJECT_ROOT
from myra_app.librarian_core import LibrarianCore
from myra_app.schema_registry import SchemaRegistry

SCHEMA_DIR = os.path.join(PROJECT_ROOT, "schema")

# On-disk sidecars that are NOT in DB_MAP but dumped anyway (flagged unregistered).
UNREGISTERED_DB_FILES = ["myra_news.db", "myra_portfolio.db"]


def open_read_only(db_path: str) -> sqlite3.Connection:
    """Open a DB in read-only mode via sqlite3 URI. Writing is impossible."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.execute("PRAGMA query_only=ON")
    return conn


def dump_ddl(conn: sqlite3.Connection) -> str:
    """Return all CREATE TABLE / CREATE INDEX statements, no internal shadow tables."""
    rows = conn.execute(
        """
        SELECT type, name, sql FROM sqlite_master
        WHERE sql IS NOT NULL
          AND type IN ('table', 'index')
          AND name NOT LIKE 'sqlite_%'
        ORDER BY CASE type WHEN 'table' THEN 1 ELSE 2 END, name
        """
    ).fetchall()
    stmts = [r[2].strip() for r in rows]
    return "\n\n".join(stmts) + "\n" if stmts else ""


def table_info(conn: sqlite3.Connection, table: str) -> list[dict]:
    """Return column metadata for one table."""
    cols = []
    for row in conn.execute(f'PRAGMA table_info("{table}")'):
        # Newer SQLite returns 6 columns: cid, name, type, notnull, dflt_value, pk.
        cid, name, typ, notnull, _dflt, pk = row[:6]
        cols.append(
            {"name": name, "type": typ, "notnull": bool(notnull), "pk": bool(pk)}
        )
    return cols


def row_count(conn: sqlite3.Connection, table: str) -> int:
    return conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]


def manifest_tables(conn: sqlite3.Connection) -> list[dict]:
    tables = conn.execute(
        """
        SELECT name FROM sqlite_master
        WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    out = []
    for (t,) in tables:
        out.append(
            {
                "name": t,
                "columns": table_info(conn, t),
                "row_count": row_count(conn, t),
            }
        )
    return out


def sql_file_content(filename: str, dbname: str, is_registered: bool, ddl: str) -> str:
    """Byte-identical copy of the schema/<dbname>.sql body dump_schema writes."""
    return (
        f"-- MYRA schema dump: {filename} ({dbname})\n"
        f"-- {'UNREGISTERED in DB_MAP' if not is_registered else 'Registered in DB_MAP'}\n"
        f"-- Generated by scripts/dump_schema.py\n"
        "-- Read-only dump: DDL only, no row data.\n\n"
        f"{ddl}"
    )


def manifest_json(manifest: dict) -> str:
    """Byte-identical copy of the schema/schema_manifest.json body dump_schema writes."""
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def generate_schema_outputs(
    db_dir: str,
) -> tuple[dict[str, str], dict, list[str], list[str], list[str]]:
    """Compute everything dump_schema would write, without writing anything.

    Returns (files, manifest, mismatches, missing, unreadable) where:
      * files      - relative filename -> full file content for every artifact
                     (schema/<dbname>.sql per live DB + schema_manifest.json).
      * manifest   - the manifest dict (used to derive sql_content / manifest_json).
      * mismatches - SchemaRegistry cross-check lines (report only).
      * missing    - dbnames whose DB file was not found under db_dir.
      * unreadable - dbnames that exist but could not be opened cleanly
                     (malformed/locked image); they are skipped, not fatal.
                     This keeps the pre-commit drift guard stable when git
                     stashes tracked WAL/SHM sidecars mid-commit.
    """
    registered = [(k, v) for k, v in LibrarianCore.DB_MAP.items()]
    unregistered = [(os.path.splitext(f)[0], f) for f in UNREGISTERED_DB_FILES]

    files: dict[str, str] = {}
    manifest: dict = {}
    mismatches: list[str] = []
    missing: list[str] = []
    unreadable: list[str] = []

    for dbname, filename in registered + unregistered:
        is_registered = dbname in LibrarianCore.DB_MAP
        db_path = os.path.join(db_dir, filename)

        if not os.path.exists(db_path):
            manifest[dbname] = {
                "file": filename,
                "registered": is_registered,
                "note": "missing on disk (skipped)",
                "tables": [],
            }
            missing.append(dbname)
            continue

        try:
            conn = open_read_only(db_path)
            try:
                ddl = dump_ddl(conn)
                tables = manifest_tables(conn)
            finally:
                conn.close()
        except sqlite3.DatabaseError as exc:
            manifest[dbname] = {
                "file": filename,
                "registered": is_registered,
                "note": f"unreadable (skipped): {exc}",
                "tables": [],
            }
            unreadable.append(dbname)
            continue

        files[f"{dbname}.sql"] = sql_file_content(filename, dbname, is_registered, ddl)
        manifest[dbname] = {
            "file": filename,
            "registered": is_registered,
            "tables": tables,
        }

        # Cross-check against SchemaRegistry. Runs for registered AND
        # unregistered DBs so that deliberately-registered tables in an
        # unregistered DB (e.g. myra_portfolio.*) are not blindly flagged.
        registry_tables = {
            info.get("table", t)
            for t, info in SchemaRegistry.TABLES.items()
            if info.get("db") == dbname
        }
        disk_tables = {t["name"] for t in tables}

        for t in sorted(disk_tables - registry_tables):
            if is_registered:
                mismatches.append(f"{dbname}.{t}: on disk but not in SchemaRegistry")
            else:
                mismatches.append(
                    f"unregistered DB {dbname} ({filename}): table {t} on disk but "
                    f"not in SchemaRegistry"
                )
        for t in sorted(registry_tables - disk_tables):
            mismatches.append(f"{dbname}.{t}: in SchemaRegistry but not on disk")

    files["schema_manifest.json"] = manifest_json(manifest)
    return files, manifest, mismatches, missing, unreadable


def main() -> int:
    os.makedirs(SCHEMA_DIR, exist_ok=True)
    files, manifest, mismatches, _missing, unreadable = generate_schema_outputs(DB_DIR)

    for rel, content in files.items():
        with open(os.path.join(SCHEMA_DIR, rel), "w", encoding="utf-8") as fh:
            fh.write(content)
        if rel.endswith(".sql"):
            dbname = os.path.splitext(rel)[0]
            tables = manifest[dbname]["tables"]
            print(
                f"[ok] {manifest[dbname]['file']:<28} -> schema/{rel}  "
                f"({len(tables)} tables)"
            )

    for dbname in _missing:
        print(f"[warn] {manifest[dbname]['file']} not found under {DB_DIR} — skipped.")

    for dbname in unreadable:
        print(
            f"[warn] {manifest[dbname]['file']} exists but is unreadable "
            f"({manifest[dbname]['note']}) — skipped, schema NOT regenerated for it."
        )

    print(f"\nWrote schema/schema_manifest.json ({len(manifest)} DBs)")
    print("Registered in DB_MAP:", sum(1 for m in manifest.values() if m["registered"]))
    extras = [m["file"] for m in manifest.values() if not m["registered"]]
    print("On-disk but unregistered in DB_MAP:", ", ".join(extras))

    if mismatches:
        print(
            "\n--- SchemaRegistry cross-check mismatches (report only, not fixed) ---"
        )
        for m in sorted(mismatches):
            print("  " + m)
    else:
        print("\nSchemaRegistry cross-check: no mismatches.")

    # Deterministic exit: mismatches are informational in the committed files,
    # so they do not change the exit code.
    return 0


if __name__ == "__main__":
    sys.exit(main())
